/***************************************************************************
* Program:		be_spec_dumper.c
* Function:		Generates and dumps the specification for the ia32 backend
*				for each generated pattern.
* Depends on:	Needs the analysis info generated by the pattern creator
* Author:		Andreas Schoesser
* Date:			2007-03-02
***************************************************************************/


// ---------------------------- INCLUDES --------------------------------

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "simd_presets.h"

#include "irgraph.h"
#include "pmap.h"

#include "create_pattern_t.h"
#include "be_spec_dumper.h"




/************************************************************************
 * Inits the backend specification dumper
 * Generates a new file and with a header
 * Returns:	a be_spec_env_t structure which has to be passed to all
 *			spec_dumper functions
 ************************************************************************/

be_spec_env_t *init_be_spec()
{
	be_spec_env_t *be_spec_env = malloc(sizeof(be_spec_env_t));
	FILE *fp = fopen(BE_SPEC_FILE, "wt");

	fprintf(fp, "# This file is generated! Do not edit, your changes will be lost!\n");
	fprintf(fp, "#  ___ _____  _____                  _                               _\n");
	fprintf(fp, "# / ___/ ___|| ____| __   _____  ___| |_ ___  _ __   _ __   ___   __| | ___  ___\n");
	fprintf(fp, "# \\___ \\___ \\|  _|   \\ \\ / / _ \\/ __| __/ _ \\| '__| | '_ \\ / _ \\ / _` |/ _ \\/ __|\n");
	fprintf(fp, "#  ___) |__) | |___   \\ V /  __/ (__| || (_) | |    | | | | (_) | (_| |  __/\\__ \\\n");
	fprintf(fp, "# |____/____/|_____|   \\_/ \\___|\\___|\\__\\___/|_|    |_| |_|\\___/ \\__,_|\\___||___/\n\n");

	be_spec_env -> output_file = fp;
	return(be_spec_env);
}




/************************************************************************
 * Dumps the backend specification of a rich instruction depending
 * on the analysis information of the pattern creator
 ************************************************************************/

void dump_be_spec(be_spec_env_t *be_spec_env, graph_ana_info_t *graph_ana_info, int uses_memory)
{
	argument_descr_t *arguments[MAX_SIMD_ARGUMENTS + 2];
	pmap_entry *entry, *entry2;
	int max_argument = -1000, i;
	char irg_name[255];
	int mem_slot = (uses_memory) ? 1 : 0;
	FILE *fp = be_spec_env->output_file;

	// Order the arguments according to their arg_nr
	memset(arguments, 0, sizeof(arguments));
	pmap_foreach(graph_ana_info->argument_nodes, entry)
	{
		argument_descr_t *argument = entry->value;

		if(argument->arg_nr > -2)
		{
			assert(argument->arg_nr + 1 < MAX_SIMD_ARGUMENTS + 1);
			arguments[argument->arg_nr + 1] = argument;
			if(argument->arg_nr + 1 > max_argument)
				max_argument = argument->arg_nr + 1;
		}

	}

	get_rule_name(graph_ana_info, irg_name);
	fprintf(fp, "$nodes{\"%s\"} = {\n", irg_name);

	// Dump the in-register requirements
	fprintf(fp, "  \"reg_req\"  => { \"in\" => [ ");
	for(i = 1; i <= max_argument; i++)
		fprintf(fp, "\"%s\", ", arguments[i]->register_class);
	if(uses_memory)
		fprintf(fp, "\"none\", ");

	// Dump the out-register requirements
	fprintf(fp, "], \"out\" => [ ");
	if(arguments[0] != NULL) // The result data
		fprintf(fp, "\"%s\", ", arguments[0]->register_class);
	if(uses_memory)			 // The memory out
		fprintf(fp, "\"none\", ");
	pmap_foreach(graph_ana_info->destroyed_regs, entry2)
	{
		char *destroyed_reg = (char *) entry2->value;
		fprintf(fp, "\"%s\", ", destroyed_reg);
	}
	fprintf(fp, "] }, \n");

	// Dump the emittment
	fprintf(fp, "  \"emit\" => \"%s\",\n", graph_ana_info->emit_statement);

	fprintf(fp, "};\n\n");
}




/************************************************************************
 * Frees information allocated by the backend specification dumper
 ************************************************************************/

void deinit_be_spec(be_spec_env_t *be_spec_env)
{
	fclose(be_spec_env->output_file);
	free(be_spec_env);
}
