/***********************************************************************
 * Program:		rule_info_dumper.c
 * Function:	Dumps C source code containig information about the
 *				generated GrGen rules into a .h file to be included
 *				when the compiler is recompiled to use the new GrGen
 *				rules.
 * Depends on:	Needs the analysis info generated by the pattern creator
 * Author:		Andreas Schoesser
 * Date:		2007-06-28
 ************************************************************************/


// ----------------------------- INCLUDES --------------------------------

#include <malloc.h>

#include "rule_info_dumper.h"
#include "simd_presets.h"



/************************************************************************
 * Dumps the header of the "rulenames.c" file
 * Rulenames.c contains information about
 * - Which rules are defined,
 * - Which name the assembly operation the complex operation gets
 * - Which name the backend-firmnode the complex operation gets.
 ************************************************************************/

rule_info_env_t *init_rule_info_dumper(int max_num_rules)
{
	rule_info_env_t *rule_info_env = malloc(sizeof(rule_info_env_t));
	FILE *fp = fopen(RULENAME_FILE, "wt");

	fprintf(fp, "#ifdef INCLUDE_GENERATED_PATTERNS\n");
	fprintf(fp, "typedef ir_node* (* ia32_construct_func_t) ();\n");
	fprintf(fp, "ext_grs_action_t *rules[%d];\n", max_num_rules);
	fprintf(fp, "char             *operation_names[%d];\n", max_num_rules);
	fprintf(fp, "char             *firmnode_names[%d];\n", max_num_rules);
	fprintf(fp, "int              priorities[%d][2];\n", max_num_rules);
	fprintf(fp, "ia32_construct_func_t ia32_construct_funcs[%d];\n", max_num_rules);
	fprintf(fp, "int              cost_savings[%d];\n", max_num_rules);
	fprintf(fp, "\n");
	fprintf(fp, "void fill_rulename_array()\n{\n");

	rule_info_env->output_file = fp;
	rule_info_env->num_rules = 0;
	return(rule_info_env);
}



/************************************************************************
 * Dumps the above information for each rule.
 ************************************************************************/

void dump_rule_info(rule_info_env_t *rule_info_env, graph_ana_info_t *graph_ana_info, int arity)
{
	FILE *fp = rule_info_env->output_file;
	char name[255];
	const char *firmnode_name;
	int i = rule_info_env->num_rules;

	get_rule_name(graph_ana_info, name);
	firmnode_name = name;

	fprintf(fp, "  {\n");
	fprintf(fp, "    extern ext_grs_action_t *ext_grs_action_complex_instructions_%s;\n", name);
	fprintf(fp, "    extern ia32_construct_func_t new_rd_ia32_%s;\n", firmnode_name);
	fprintf(fp, "    rules[%d] = ext_grs_action_complex_instructions_%s;\n", i, name);
	fprintf(fp, "    firmnode_names[%d] = \"%s\";\n", i, firmnode_name);
	fprintf(fp, "    ia32_construct_funcs[%d] = (ia32_construct_func_t) &new_rd_ia32_%s;\n", i, firmnode_name);
	fprintf(fp, "    priorities[%d][0] = %d;\n", i, i);
	fprintf(fp, "    priorities[%d][1] = %d;\n", i, graph_ana_info->priority);
	fprintf(fp, "    cost_savings[%d] = %d;\n", i, graph_ana_info->cost_savings);
	fprintf(fp, "  }\n");

	rule_info_env->num_rules++;
}



/************************************************************************
 * Frees information used by the rule_info_dumper instance
 ************************************************************************/

void deinit_rule_info_dumper(rule_info_env_t *rule_info_env)
{
	FILE *fp = rule_info_env->output_file;

	// Dump footer of rule pointers file
	fprintf(fp, "}\n\n");
	fprintf(fp, "#define NUM_RULES %d\n\n#endif\n", rule_info_env->num_rules);

	fclose(rule_info_env->output_file);
	free(rule_info_env);
}
