/**
 * @file
 * @brief    Additional data modes for VHDL output.
 * @author   Andreas Seltenreich
 *
 * Define signed and unsigned integer modes w/ sizes at bit
 * granularity to allow efficient hardware synthetisation.
 *
 */

#include <firm.h>

#define vhdl_def_mode(bits) \
  ir_mode *mode_V ## bits ## u;						\
  ir_mode *get_modeV ## bits ## u (void) { return mode_V ## bits ## u; } \
  ir_mode *mode_V ## bits ## s;						\
  ir_mode *get_modeV ## bits ## s (void) { return mode_V ## bits ## s; } \

vhdl_def_mode(1)
vhdl_def_mode(2)
vhdl_def_mode(3)
vhdl_def_mode(4)
vhdl_def_mode(5)
vhdl_def_mode(6)
vhdl_def_mode(7)
vhdl_def_mode(8)
vhdl_def_mode(9)
vhdl_def_mode(10)
vhdl_def_mode(11)
vhdl_def_mode(12)
vhdl_def_mode(13)
vhdl_def_mode(14)
vhdl_def_mode(15)
vhdl_def_mode(16)
vhdl_def_mode(17)
vhdl_def_mode(18)
vhdl_def_mode(19)
vhdl_def_mode(20)
vhdl_def_mode(21)
vhdl_def_mode(22)
vhdl_def_mode(23)
vhdl_def_mode(24)
vhdl_def_mode(25)
vhdl_def_mode(26)
vhdl_def_mode(27)
vhdl_def_mode(28)
vhdl_def_mode(29)
vhdl_def_mode(30)
vhdl_def_mode(31)
vhdl_def_mode(32)
vhdl_def_mode(33)
vhdl_def_mode(34)
vhdl_def_mode(35)
vhdl_def_mode(36)
vhdl_def_mode(37)
vhdl_def_mode(38)
vhdl_def_mode(39)
vhdl_def_mode(40)
vhdl_def_mode(41)
vhdl_def_mode(42)
vhdl_def_mode(43)
vhdl_def_mode(44)
vhdl_def_mode(45)
vhdl_def_mode(46)
vhdl_def_mode(47)
vhdl_def_mode(48)
vhdl_def_mode(49)
vhdl_def_mode(50)
vhdl_def_mode(51)
vhdl_def_mode(52)
vhdl_def_mode(53)
vhdl_def_mode(54)
vhdl_def_mode(55)
vhdl_def_mode(56)
vhdl_def_mode(57)
vhdl_def_mode(58)
vhdl_def_mode(59)
vhdl_def_mode(60)
vhdl_def_mode(61)
vhdl_def_mode(62)
vhdl_def_mode(63)
vhdl_def_mode(64)

#define vhdl_init_mode(bits) \
  mode_V ## bits ## u  = new_int_mode("V" #bits "u",  irma_twos_complement, bits,   0, 32); \
  mode_V ## bits ## u  = new_int_mode("V" #bits "s",  irma_twos_complement, bits,   1, 32);\

void init_vhdl_modes(void)
{
  vhdl_init_mode(1)
  vhdl_init_mode(2)
  vhdl_init_mode(3)
  vhdl_init_mode(4)
  vhdl_init_mode(5)
  vhdl_init_mode(6)
  vhdl_init_mode(7)
  vhdl_init_mode(8)
  vhdl_init_mode(9)
  vhdl_init_mode(10)
  vhdl_init_mode(11)
  vhdl_init_mode(12)
  vhdl_init_mode(13)
  vhdl_init_mode(14)
  vhdl_init_mode(15)
  vhdl_init_mode(16)
  vhdl_init_mode(17)
  vhdl_init_mode(18)
  vhdl_init_mode(19)
  vhdl_init_mode(20)
  vhdl_init_mode(21)
  vhdl_init_mode(22)
  vhdl_init_mode(23)
  vhdl_init_mode(24)
  vhdl_init_mode(25)
  vhdl_init_mode(26)
  vhdl_init_mode(27)
  vhdl_init_mode(28)
  vhdl_init_mode(29)
  vhdl_init_mode(30)
  vhdl_init_mode(31)
  vhdl_init_mode(32)
  vhdl_init_mode(33)
  vhdl_init_mode(34)
  vhdl_init_mode(35)
  vhdl_init_mode(36)
  vhdl_init_mode(37)
  vhdl_init_mode(38)
  vhdl_init_mode(39)
  vhdl_init_mode(40)
  vhdl_init_mode(41)
  vhdl_init_mode(42)
  vhdl_init_mode(43)
  vhdl_init_mode(44)
  vhdl_init_mode(45)
  vhdl_init_mode(46)
  vhdl_init_mode(47)
  vhdl_init_mode(48)
  vhdl_init_mode(49)
  vhdl_init_mode(50)
  vhdl_init_mode(51)
  vhdl_init_mode(52)
  vhdl_init_mode(53)
  vhdl_init_mode(54)
  vhdl_init_mode(55)
  vhdl_init_mode(56)
  vhdl_init_mode(57)
  vhdl_init_mode(58)
  vhdl_init_mode(59)
  vhdl_init_mode(60)
  vhdl_init_mode(61)
  vhdl_init_mode(62)
  vhdl_init_mode(63)
  vhdl_init_mode(64)
}
