/**
 * @file
 * @brief     Function prototypes for the machine description.
 * @note      DO NOT EDIT THIS FILE, your changes will be lost.
 *            Edit libfirm/ir/be/sparc/sparc_spec.pl instead.
 *            created by: libfirm/ir/be/scripts/generate_machine.pl libfirm/ir/be/sparc/sparc_spec.pl libfirm/ir/be/sparc
 * @date      Tue Dec 15 15:19:15 2009
 */
#ifndef FIRM_BE_SPARC_GEN_SPARC_MACHINE_H
#define FIRM_BE_SPARC_GEN_SPARC_MACHINE_H

#include "../bemachine.h"

/**
 * Returns the sparc machine description.
 */
const be_machine_t *sparc_init_machine_description(void);



#endif
