/**
 * @file
 * @brief     Generated functions for machine description interface.
 * @note      DO NOT EDIT THIS FILE, your changes will be lost.
 *            Edit libfirm/ir/be/sparc/sparc_spec.pl instead.
 *            created by: libfirm/ir/be/scripts/generate_machine.pl libfirm/ir/be/sparc/sparc_spec.pl libfirm/ir/be/sparc
 * @date      Tue Dec 15 15:19:15 2009
 */
#include "config.h"

#include "gen_sparc_machine.h"


be_execution_unit_type_t sparc_execution_unit_types[] = {
};

be_machine_t sparc_cpu = {
	3,
	1,
	0,
	sparc_execution_unit_types
};

/**
 * Returns the sparc machines description
 */
const be_machine_t *sparc_init_machine_description(void) {
	static int initialized = 0;

	if (! initialized) {
		be_execution_unit_type_t *cur_unit_tp;
		(void) cur_unit_tp; /* avoid warning */

		be_machine_init_dummy_unit();

		initialized = 1;
	}

	return &sparc_cpu;
}
