/**
 * @file
 * @brief     Generated functions to emit code for assembler ir nodes.
 * @note      DO NOT EDIT THIS FILE, your changes will be lost.
 *            Edit libfirm/ir/be/sparc/sparc_spec.pl instead.
 *            created by: libfirm/ir/be/scripts/generate_emitter.pl libfirm/ir/be/sparc/sparc_spec.pl libfirm/ir/be/sparc
 * @date      Tue Dec 15 15:19:15 2009
 */
#include "config.h"

#include <stdio.h>

#include "irnode.h"
#include "irop_t.h"
#include "irprog_t.h"

#include "gen_sparc_emitter.h"
#include "sparc_new_nodes.h"
#include "sparc_emitter.h"

static void emit_sparc_SubSP(const ir_node *node) {
	be_emit_cstring("\tadd ");
	sparc_emit_source_register(node, 0);
	be_emit_cstring(", ");
	sparc_emit_source_register(node, 1);
	be_emit_cstring(", ");
	sparc_emit_dest_register(node, 0);
	be_emit_finish_line_gas(node);
}

static void emit_sparc_Add(const ir_node *node) {
	be_emit_cstring("\tadd ");
	sparc_emit_source_register(node, 0);
	be_emit_cstring(", ");
	sparc_emit_reg_or_imm(node, 1);
	be_emit_cstring(", ");
	sparc_emit_dest_register(node, 0);
	be_emit_finish_line_gas(node);
}

static void emit_sparc_Store(const ir_node *node) {
	be_emit_cstring("\tst");
	sparc_emit_store_mode(node);
	be_emit_char(' ');
	sparc_emit_source_register(node, 0);
	be_emit_cstring(", [");
	sparc_emit_dest_register(node, 0);
	sparc_emit_offset(node);
	be_emit_char(']');
	be_emit_finish_line_gas(node);
}

static void emit_sparc_Mov(const ir_node *node) {
	be_emit_cstring("\tmov ");
	sparc_emit_reg_or_imm(node, 0);
	be_emit_cstring(", ");
	sparc_emit_dest_register(node, 0);
	be_emit_finish_line_gas(node);
}

static void emit_sparc_Tst(const ir_node *node) {
	be_emit_cstring("\ttst ");
	sparc_emit_source_register(node, 0);
	be_emit_finish_line_gas(node);
}

static void emit_sparc_Cmp(const ir_node *node) {
	be_emit_cstring("\tcmp ");
	sparc_emit_source_register(node, 0);
	be_emit_cstring(", ");
	sparc_emit_reg_or_imm(node, 1);
	be_emit_finish_line_gas(node);
}

static void emit_sparc_Sub(const ir_node *node) {
	be_emit_cstring("\tsub ");
	sparc_emit_source_register(node, 0);
	be_emit_cstring(", ");
	sparc_emit_reg_or_imm(node, 1);
	be_emit_cstring(", ");
	sparc_emit_dest_register(node, 0);
	be_emit_finish_line_gas(node);
}

static void emit_sparc_Load(const ir_node *node) {
	be_emit_cstring("\tld");
	sparc_emit_load_mode(node);
	be_emit_cstring(" [");
	sparc_emit_source_register(node, 0);
	sparc_emit_offset(node);
	be_emit_cstring("], ");
	sparc_emit_dest_register(node, 0);
	be_emit_finish_line_gas(node);
}

static void emit_sparc_AddSP(const ir_node *node) {
	be_emit_cstring("\tsub ");
	sparc_emit_source_register(node, 0);
	be_emit_cstring(", ");
	sparc_emit_source_register(node, 1);
	be_emit_cstring(", ");
	sparc_emit_dest_register(node, 0);
	be_emit_finish_line_gas(node);
}

/**
 * Enters the emitter functions for handled nodes into the generic
 * pointer of an opcode.
 */
void sparc_register_spec_emitters(void) {

#define BE_EMIT(a) op_sparc_##a->ops.generic = (op_func)emit_sparc_##a

  /* generated emitter functions */
  BE_EMIT(SubSP);
  BE_EMIT(Add);
  BE_EMIT(Store);
  BE_EMIT(Mov);
  BE_EMIT(Tst);
  BE_EMIT(Cmp);
  BE_EMIT(Sub);
  BE_EMIT(Load);
  BE_EMIT(AddSP);

#undef BE_EMIT
}
