/**
 * @file
 * @brief Function prototypes for the emitter functions.
 * @note  DO NOT EDIT THIS FILE, your changes will be lost.
 *        Edit libfirm/ir/be/sparc/sparc_spec.pl instead.
 *        created by: libfirm/ir/be/scripts/generate_emitter.pl libfirm/ir/be/sparc/sparc_spec.pl libfirm/ir/be/sparc
 * @date  Tue Dec 15 15:19:15 2009
 */
#ifndef FIRM_BE_SPARC_GEN_SPARC_EMITTER_H
#define FIRM_BE_SPARC_GEN_SPARC_EMITTER_H

#include "irnode.h"
#include "sparc_emitter.h"

void sparc_register_spec_emitters(void);

#endif
